[package]
name = "bassline"
version = "0.1.0"
authors = ["K <k@pods.lv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.21"
futures = "0.3.5"
irc = "0.14.0"
rusqlite = "0.23.1"
encoding="0.2.33"