[package]
name = "bassline"
version = "0.1.0"
authors = ["K <k@pods.lv>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.21", features = ["macros", "time"] }
futures = "0.3.5"
irc = { version = "0.14.0", default-features = false, features = ["ctcp", "toml_config"] }
rusqlite = "0.23.1"
encoding="0.2.33"